---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# metabroom

The goal of metabroom is to `broom` meta-analysis models produced by `metafor`. That is, when I finish it.  

See the `testing` file to see where I'm at. 

## Example

### Get example dataset

```{r Get a test model}
# Hmmm. What's best practice for loading %>% in packages? What's best practice for package dependencies?
library(tidyverse)
library(metafor)
library(metabroom)

example_ma <- data("dat.normand1999", package = "metafor") %>% # Get an example dataset.
  get() %>% # NB: slab (i.e., study) := "source".
  metafor::escalc( # Calculate effect.
    measure = "SMD",
    n1i = n1i,
    m1i =m1i,
    sd1i = sd1i,
    n2i = n2i,
    m2i = m2i,
    sd2i = sd2i,
    data = .
  ) %>% 
  metafor::rma( # Meta-analyse!
    slab = source
  ) 

# Check all is as it should be.
example_ma %>% 
  metafor::forest()

```

```{r}
library(tidyverse)
```


### `augment`

```{r augment}
example_ma %>% augment()
```

### `tidy`

```{r tidy}
example_ma %>% tidy()
```

### `glance`

```{r glance}
example_ma %>% glance()
```

